name: WorldGuardExtraFlags
description: Adds more flags to WorldGuard to help manage your server easily!

version: 4.2.3
api-version: 1.13

author: isokissa3
website: https://joniaromaa.fi

depend: [ WorldGuard ]
softdepend: [ ProtocolLib ]

main: net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin