name: WorldGuardExtraFlags
description: Adds more flags to WorldGuard to help manage your server easily!


folia-supported: true

version: 4.2.3-SNAPSHOT

api-version: 1.13

author: isokissa3
website: https://goldtreevers.net

depend: [ WorldGuard ]
softdepend: [ ProtocolLib ]

main: net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin